
import { HouseOfficer } from "@/types/HouseOfficer";
import { format } from "date-fns";

export const exportToPDF = (houseOfficers: HouseOfficer[]) => {
  const signerName = prompt("Enter your full name for e-signature:");
  
  if (!signerName) {
    alert("E-signature name is required for PDF export.");
    return;
  }

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  
  if (!printWindow) {
    alert("Please allow popups for PDF export to work.");
    return;
  }

  const currentDate = format(new Date(), "MMMM dd, yyyy 'at' hh:mm a");
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>House Officers Report</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 20px;
          line-height: 1.4;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          border-bottom: 2px solid #333;
          padding-bottom: 20px;
        }
        .header h1 {
          margin: 0;
          color: #333;
          font-size: 18px;
        }
        .header h2 {
          margin: 5px 0;
          color: #666;
          font-size: 16px;
        }
        .header h3 {
          margin: 5px 0;
          color: #666;
          font-size: 14px;
        }
        .meta-info {
          margin-bottom: 20px;
          padding: 10px;
          background-color: #f5f5f5;
          border-radius: 5px;
        }
        .officers-table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 30px;
        }
        .officers-table th,
        .officers-table td {
          border: 1px solid #ddd;
          padding: 8px;
          text-align: left;
          font-size: 12px;
        }
        .officers-table th {
          background-color: #f8f9fa;
          font-weight: bold;
        }
        .officers-table tr:nth-child(even) {
          background-color: #f9f9f9;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 2px solid #333;
          text-align: center;
        }
        .signature-section {
          margin-top: 30px;
          text-align: right;
        }
        @media print {
          body { margin: 0; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>FMC UMUAHIA, ABIA STATE</h1>
        <h2>DEPARTMENT OF INTERNAL MEDICINE</h2>
        <h3>HOUSE OFFICERS CLINICAL FLOW</h3>
      </div>
      
      <div class="meta-info">
        <strong>Report Generated:</strong> ${currentDate}<br>
        <strong>Total House Officers:</strong> ${houseOfficers.length}<br>
        <strong>Generated by:</strong> ${signerName}
      </div>

      <table class="officers-table">
        <thead>
          <tr>
            <th>Full Name</th>
            <th>Gender</th>
            <th>Unit Assigned</th>
            <th>Date Signed In</th>
            <th>Clinical Presentation Topic</th>
            <th>Presentation Date</th>
            <th>Expected Sign-Out</th>
          </tr>
        </thead>
        <tbody>
          ${houseOfficers.map(officer => `
            <tr>
              <td>${officer.fullName}</td>
              <td>${officer.gender}</td>
              <td>${officer.unitAssigned}</td>
              <td>${format(new Date(officer.dateSignedIn), "MMM dd, yyyy")}</td>
              <td>${officer.clinicalPresentationTopic}</td>
              <td>${format(new Date(officer.clinicalPresentationDate), "MMM dd, yyyy")}</td>
              <td>${format(new Date(officer.expectedSignOutDate), "MMM dd, yyyy")}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="signature-section">
        <p><strong>E-Signature:</strong> ${signerName}</p>
        <p><strong>Date:</strong> ${currentDate}</p>
      </div>

      <div class="footer">
        <p>Built by Dr. Onyemachi Joseph, copyright 2025</p>
      </div>

      <script>
        window.onload = function() {
          window.print();
          setTimeout(() => window.close(), 1000);
        };
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
};
